Feat createTrip
bertacume/gtpe-client pull request #11
Opened 2018-11-30 17:14 UTC by bertacume

2018-11-30 17:31 UTC, ArtyBMPS commented on thesis-fe/src/components/apollo/mutations/create_trip.js
> +  createTrip(trip: $trip, userID: "5bffbe8ff59a127f1afadf18") {
userID should not be hardcoded

2018-11-30 17:32 UTC, ArtyBMPS approved these changes

2018-12-01 13:26 UTC, ArtyBMPS requested changes
please fix the add trip id

2018-12-01 13:28 UTC, bertacume commented on thesis-fe/src/components/apollo/mutations/create_trip.js
> +  createTrip(trip: $trip, userID: "5bffbe8ff59a127f1afadf18") {
True, I'm gonna delete this field and as its not required the mutation should work

2018-12-01 13:30 UTC, ArtyBMPS approved these changes

2018-12-01 13:30 UTC, ArtyBMPS commented on thesis-fe/src/components/apollo/mutations/create_trip.js
> +  createTrip(trip: $trip) {
Great

2018-12-01 13:30 UTC, merged